# Generated by Django 3.2.4 on 2021-06-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('USER_LOGGED_IN', 'Пользователь вошел'), ('USER_REGISTERED', 'Пользователь зарегестрировался'), ('USER_RESET_PASSWORD', 'Пользователь восстановил пароль'), ('RESET_PASSWORD_REQUESTED', 'Пользователь запросил смену пароля'), ('USER_UPDATED', 'Пользователь обновлен')], max_length=255)),
            ],
        ),
    ]
