# Generated by Django 3.2.4 on 2021-06-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210616_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='activity',
            new_name='event',
        ),
    ]
