version: "3.4"

services:

    db:
      image: postgres:12-alpine
      env_file:
        - .env

    web:
      build: .
      command: poetry run python3 manage.py runserver 0.0.0.0:8000
      environment:
        - POSTGRES_HOST=db
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - db

