# Generated by Django 3.2.5 on 2021-08-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResetToken',
        ),
    ]
