# Generated by Django 3.2.12 on 2022-02-14 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwt', '0003_delete_resettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='parent_token',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitution_token', to='jwt.refreshtoken'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
