# Generated by Django 3.2.11 on 2022-02-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwt', '0003_delete_resettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='parent_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jwt.refreshtoken'),
        ),
    ]
